---
- include: "burp.yml"
- name: "Installing Firefox PlugIns"
  template:
    src: "templates/policies.json.j2"
    dest: "/usr/share/firefox-esr/distribution/policies.json"
  become: true
  become_method: sudo
