---
- name: "Customizing Kali"
  hosts: localhost
  connection: local
  roles:
    - role: "roles/configure-gdb"
    - role: "roles/configure-ghidra"
    - role: "roles/get-additional-tools-binex"
    - role: "roles/customize-firefox"
