---
- name: "Customizing Kali"
  hosts: localhost
  connection: local
  roles:
    - role: "roles/configure-gdb"
    - role: "roles/configure-ghidra"
    - role: "roles/get-additional-tools-binex"
    - role: "roles/customize-firefox"
#    - role: gantsign.visual-studio-code
#      users:
#        - username: "{{ ansible_user_id }}" 
#          visual_studio_code_extensions:
#            - streetsidesoftware.code-spell-checker
#            - bierner.docs-view
#            - ms-python.python
#            - ms-vscode.cpptools
#            - DEVSENSE.phptools-vscode
